accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout')
]

blog/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),

    path('api/post/', include('post.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),
]

post/api/urls.py
from django.urls import path
from post.api.views import (
	
	api_detail_post_view, 
	api_update_post_view,
	api_delete_post_view,
	api_create_post_view,
	ApiBlogListView,

)

app_name = 'post'

urlpatterns = [
	path('<str:slug>/detail/', api_detail_post_view, name='detail'),
	path('<str:slug>/update/', api_update_post_view, name='update'),
	path('<str:slug>/delete/', api_delete_post_view, name='delete'),
	path('create/', api_create_post_view, name='create'),
	path('list/', ApiBlogListView.as_view(), name='list'),
]

post/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name='index'),
    path('<str:slug>/detail/', post_detail, name='detail'),
    path('create/', post_create, name='create'),
    path('<str:slug>/update/', post_update, name='update'),
    path('<str:slug>/delete/', post_delete, name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify



class Post(models.Model):
	title = models.CharField(max_length=100, verbose_name='Başlık')
	text = models.TextField(verbose_name='Metin')
	date = models.DateTimeField(verbose_name="Tarih", auto_now_add=True)
	slug = models.SlugField(unique=True, editable= False, max_length=130)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('post:detail', kwargs={'slug': self.slug})

	def get_unique_slug(self):
		slug = slugify(self.title.replace('ı', 'i'))
		unique_slug = slug
		counter = 1
		while Post.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, counter)
			counter += 1
		return unique_slug

	def save(self, *args, **kwargs):
		self.slug = self.get_unique_slug()
		return super(Post, self).save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

class LoginForm(forms.Form):
	username = forms.CharField(max_length=20, label='Kullanıcı Adı')
	password = forms.CharField(max_length=20, label='Parola', widget=forms.PasswordInput)

	def clean(self):
		username = self.cleaned_data.get('username')
		password = self.cleaned_data.get('password')
		if username and password:
			user = authenticate(username=username, password=password)
			if not user:
				raise forms.ValidationError('Kullanıcı adı ya da parola yanlış girildi.')
		return super(LoginForm, self).clean()


class RegisterForm(forms.ModelForm):
	username = forms.CharField(max_length=20, label='Kullanıcı Adı')
	password = forms.CharField(max_length=20, label='Parola', widget=forms.PasswordInput)
	confirm_password = forms.CharField(max_length=20, label='Parola (Tekrar)', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = [
			'username',
			'password',
			'confirm_password',
		]

	def clean_confirm_password(self):
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')
		if password and confirm_password and password != confirm_password:
			raise forms.ValidationError('Parolalar eşleşmiyor.')
		return confirm_password

	@receiver(post_save, sender=settings.AUTH_USER_MODEL)
	def create_auth_token(sender, instance=None, created=False, **kwargs):
		if created:
			Token.objects.create(user=instance)

post/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            'title',
            'text',
        ]

accounts/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.authtoken.models import Token
from accounts.api.serializers import RegistrationSerializer


@api_view(['POST'],)
def registration_view(request):
	if request.method == 'POST':
		serializer = RegistrationSerializer(data=request.data)
		data = {}
		if serializer.is_valid():
			account = serializer.save()
			data['response'] = 'successfully registered a new user.'
			data['username'] = account.username
			token = Token.objects.get(user=account).key
			data['token'] = token
		else:
			data = serializers.errors
		return Response(data)

accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, RegisterForm
from django.contrib.auth import authenticate, login, logout


def login_view(request):
	form = LoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		login(request, user)
		return redirect('home')
	context = {
		'form': form,
		'title': 'Giriş Yap'
	}
	return render(request, 'account_form.html', context)


def register_view(request):
	form = RegisterForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get('password')
		user.set_password(password)
		user.save()
		new_user = authenticate(username=user.username, password=password)
		login(request, new_user)
		return redirect('home')
	context = {
		'form': form,
		'title': 'Kayıt Ol'
	}
	return render(request, 'account_form.html', context)


def logout_view(request):
	logout(request)
	return redirect('home')

home/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home.html')

post/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.pagination import PageNumberPagination
from rest_framework.generics import ListAPIView
from rest_framework.authentication import TokenAuthentication
from rest_framework.filters import SearchFilter, OrderingFilter

from post.models import Post
from post.api.serializers import PostSerializer


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_detail_post_view(request, slug):
	try:
		post = Post.objects.get(slug=slug)
	except Post.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = PostSerializer(post)
		return Response(serializer.data)


@api_view(['PUT',])
@permission_classes((IsAuthenticated, IsAdminUser,))
def api_update_post_view(request, slug):
	try:
		post = Post.objects.get(slug=slug)
	except Post.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'PUT':
		serializer = PostSerializer(post, data=request.data)
		data = {}
		if serializer.is_valid():
			serializer.save()
			data['success'] = 'update successful'
			return Response(data=data)
		return Response(serializer.errors, status=status.HTTP_404_NOT_FOUND)


@api_view(['DELETE',])
@permission_classes((IsAuthenticated, IsAdminUser,))
def api_delete_post_view(request, slug):
	try:
		post = Post.objects.get(slug=slug)
	except Post.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'DELETE':
		operation = post.delete()
		data = {}
		if operation:
			data['success'] = 'delete successful'
		else:
			data['failure'] = 'delete failed'
		return Response(data=data)


@api_view(['POST',])
@permission_classes((IsAuthenticated, IsAdminUser,))
def api_create_post_view(request, slug):
	if request.method == 'POST':
		serializer = PostSerializer(post, data=request.data)
		if serializer.is_valid:
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_404_BAD_REQUEST)


class ApiBlogListView(ListAPIView):
	queryset = Post.objects.all()
	serializer_class = PostSerializer
	authentication_classes = (TokenAuthentication,)
	permission_classes = (IsAuthenticated,)
	pagination_class = PageNumberPagination
	filters_backends = (SearchFilter, OrderingFilter)
	search_fields = ('title', 'text',)

post/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, redirect
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.utils.text import slugify


def post_index(request):
    posts = Post.objects.all()
    return render(request, 'index.html', {'posts': posts})


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, 'post.html', context)


def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        post = form.save()
        messages.success(request, 'Başarılı bir şekilde kaydedildi!')
        return HttpResponseRedirect(post.get_absolute_url())

    context = {
        'form': form,
    }

    return render(request, 'create_post.html', context)


def post_update(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        messages.success(request, 'Başarılı bir şekilde kaydedildi!')
        return HttpResponseRedirect(post.get_absolute_url())

    context = {
        'form': form,
    }

    return render(request, 'create_post.html', context)


def post_delete(request, slug):
    if request.user.is_authenticated and request.user.is_superuser:
        post = get_object_or_404(Post, slug=slug)
        post.delete()
        return redirect('post:index')
    else:
        return redirect('home')

templates/account_form.html
{% extends 'base.html'%}

{% block content %}

<!-- Page Header -->
  <header class="masthead">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>{{ title }}</h1>
            <span class="subheading"></span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          {{ form.as_p }}

          <input class="btn btn-primary" type="submit" value="{{ title }}">

        </form>
      </div>
    </div>
  </div>

  <hr>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>A Site</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">

  <!-- Custom fonts for this template -->
  <link rel="stylesheet" href="{% static 'all.min.css' %}" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'clean-blog.min.css' %}">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Django</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Ana Sayfa</a>
          </li>

          {% if not request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Kayıt Ol</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Giriş Yap</a>
            </li>
          {% endif %}

          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'post:index' %}">Gönderiler</a>
            </li>
            {% if request.user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post:create' %}">Gönderi Ekle</a>
              </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış Yap</a>
            </li>
          {% endif %}

        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p class="copyright text-muted">Web Sitemin Telif Hakkı &copy; 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'clean-blog.min.js' %}"></script>

</body>

</html>

templates/create_post.html
{% extends 'base.html'%}

{% block content %}

{% if not request.user.is_authenticated %}
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Gönderi Ekle</h1>
            <span class="subheading">Sadece adminler gönderi ekleyebilir.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% else %}
<!-- Page Header -->
  <header class="masthead">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Gönderi Ekle</h1>
            <span class="subheading"></span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}

          {{ form.as_p }}

          <input class="btn btn-primary" type="submit" value="Kaydet">

        </form>
      </div>
    </div>
  </div>

  <hr>
{% endif %}

{% endblock %}

templates/home.html
{% extends 'base.html'%}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Hoş geldiniz</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock %}

templates/index.html
{% extends 'base.html'%}

{% block content %}


{% if not request.user.is_authenticated %}
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Gönderiler</h1>
            <span class="subheading">Gönderileri görebilmek için giriş yapınız.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% else %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Gönderiler</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        {% for post in posts %}
        <div class="post-preview">
          <a href="{{ post.get_absolute_url }}">
            <h2 class="post-title">
              {{ post.title }}
            </h2>
          </a>
          <p class="post-meta">Admin tarafından gönderildi
            {{ post.date }}</p>
        </div>
        <hr>

        {% endfor %}

      </div>
    </div>
  </div>

  <hr>
{% endif %}

{% endblock %}

templates/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/post.html
{% extends 'base.html'%}

{% block content %}

{% if not request.user.is_authenticated %}
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Gönderiler</h1>
            <span class="subheading">Gönderileri görebilmek için giriş yapınız.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% else %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/post-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{ post.title }}</h1>
            <span class="meta">Admin tarafından gönderildi
              {{ post.date }}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

          {% include 'messages.html' %}

          <p>{{ post.text }}</p>
          
        </div>
      </div>
    </div>
  </article>

  <hr>
{% endif %}
  
{% endblock %}